
services:
  backend:
    build: ./back-end/proj_vans
    ports:
      - "8080:8080"
    volumes:
      - ./back-end/proj_vans:/app  # Mapeia o código local para o container
      - /app/target  # Ignora a pasta de build
    env_file: 
      - .env
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./front-end/proj_van
    ports:
      - "80:80"
    volumes:
      - ./front-end/proj_van:/app  # Mapear o código local para dentro do container
      - /app/node_modules  # Ignorar node_modules para evitar conflito
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: postgres:15.0
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
